demo:
  url-get: https://httpbin.org/get

info:
  developer:
    name: Marcel Swoboda
    email: marcel.swoboda@gmx.de

spring:
  datasource:
    url: jdbc:h2:file:E:\coding\spring-learning\demo\.h2\db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    user:
      name: user
      password: password

#kafka:
#  bootstrapAddress: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
