swagger: '2.0'
info:
  title: Demo Service
  version: 1.0.0
  description: This is the demo service
  termsOfService: 'https://guptaharsh.com/'
  contact:
    email: mailtoharshgupta@gmail.com
basePath: /demo-service/v1
host: localhost
schemes:
  - http

produces:
  - application/json

responses:
  400BadRequest:
    description: Request is not correct.
    schema:
      $ref: '#/definitions/ErrorResponse'
  404NotFound:
    description: There is no stock for given stockId.
    schema:
      $ref: '#/definitions/ErrorResponse'
  500InternalServerError:
    description: Internal Server Error.
    schema:
      $ref: '#/definitions/ErrorResponse'

paths:
  /demo:
    get:
      operationId: demoCall
      summary: Returns list of stocks
      description: |-
        Returns paginated list of stocks.
      responses:
        200:
          description: Successfull response with demo content.
          schema:
            type: string
            example: pong
        500:
          $ref: '#/responses/500InternalServerError'
  /user/{id}:
    get:
      operationId: userGetById
      summary: Returns the user
      description: |-
        Returns paginated list of stocks.
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          type: integer
      responses:
        200:
          description: Successfull response with user content.
          schema:
            $ref: '#/definitions/User'
        500:
          $ref: '#/responses/500InternalServerError'

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
        minLength: 3
        maxLength: 50
      active:
        type: boolean
    required:
      - id
      - name
      - active
  ErrorResponse:
    description: |-
      Describes common fields for error responses. There could be some extra fields.
    properties:
      code:
        description: Machine-readable error-code. Usually it's an ASCII string in upper-case.
        type: string
        minLength: 1
      message:
        description: Human-readable message description
        type: string
        minLength: 1
      timestamp:
        description: Error timestamp
        type: string
        format: 'date-time'
      path:
        description: Resource URI or path to invalid data component (json path)
        type: string
    required:
      - code
      - message
      - timestamp